MapStory/story-tools

examples/style-example.js
lib/edit/style/SLDStyleConverter.js
lib/ng/core/style/ol3StyleConverter.js
lib/ng/edit/style/services/styleChoices.js
lib/ng/edit/style/services/styleTypes.js
lib/templates/edit/style/widgets/symbol-editor.html
test/test-SLDStyleConverter.js
test/test-ol3StyleConverter.js

This would ideally work the same on the client and with SLD
Would require a means to allow the user to specify the encoding in the attributes. For example, what units other than degrees?
Needs some investigation into common encodings

investigate support for icon rotation by attribute value

---

lib/ng/edit/style/directives/directives.js

@ischneider do you have any ideas why I run into this intermittently when loading saved maps? Is a simple if statement enough, or is there a different root cause that should be handled?

scope currentEditor can be undefined

---

examples/common.js
lib/core/time/maps.js
lib/edit/style/WFSDescribeFeatureType.js
lib/ng/edit/style/directives/directives.js
lib/templates/edit/style/widgets/attribute-combo.html
lib/templates/edit/style/widgets/classify-editor.html
lib/templates/edit/style/widgets/label-editor.html

From the DescribeFeatureType response, we should story the type along with the name. For example, `type="xsd:string"`. I'm fine using XML schema types (`xsd:string`) in this case but could be persuaded to just drop the prefix. Either way, something like: `gml:PointPropertyType` kinda sucks.
This could be somewhat of an invasive, breaking change (and it's all my fault :wink:) so lets coordinate.
A fix should include extraction of any inline attribute dropdown markup[1] to a directive. And the tests I didn't write yet.
This would help address #142
[1] for example: https://github.com/MapStory/story-tools/blob/da985740eefb0831a9f03e0ca3717961689881bb/lib/templates/edit/style/widgets/label-editor.html#L4

need to get and use attribute data type

---

lib/templates/edit/style/widgets/attribute-combo.html

once you've selected a label, selecting none does not clear it

cannot unset label

---

lib/ng/core/style/ol3StyleConverter.js
test/test-ol3StyleConverter.js

This only happens as vector, as SLD it's correct

classify on vector P_MALE does not show Nevada

---

examples/common.js
examples/full-example.html
lib/core/time/maps.js
lib/edit/style/WFSDescribeFeatureType.js
lib/mapstory/MapConfig.js
lib/ng/core/pins/module.js
lib/ng/core/time/services.js
test/test-MapConfig.js
test/test-maps.js
test/test-timeServices.js

We now have 2 occurrences: in the layerInfo and as a separate entry on the layer.
I'd say we only put it in layerInfo?
And we might as well move times in there as well?

only store timeAttribute once

---

lib/edit/style/SLDStyleConverter.js
test/test-SLDStyleConverter.js

It is outputted in the SLD but does not have any visual effect anymore
```
<sld:StyledLayerDescriptor xmlns:sld="http://www.opengis.net/sld" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0"><sld:NamedLayer><sld:Name>states</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name="fill">#FF0000</sld:CssParameter><sld:CssParameter name="fill-opacity">1</sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name="stroke">#000000</sld:CssParameter><sld:CssParameter name="stroke-width">1</sld:CssParameter><sld:CssParameter name="stroke-opacity">1</sld:CssParameter><sld:CssParameter name="stroke-dasharray"/></sld:Stroke></sld:PolygonSymbolizer><sld:TextSymbolizer><sld:Label><ogc:PropertyN …
```

font family not taken into account anymore

---

examples/common.js
lib/ng/core/pins/module.js

@ischneider should we handle them more silently? We currently throw and error.
An example is mapstory map number 1193
```
StoryPin {appearance: "tr-tr?", title: "1683", content: "William Penn's colony erects a brewery at Peonshury near Bristol, Pennsylvania. ", start_time: -9043747200000, end_time: -9056793600000…}appearance: "tr-tr?"content: "William Penn's colony erects a brewery at Peonshury near Bristol, Pennsylvania. "end_time: -9056793600000id: 16073in_map: truein_timeline: truestart_time: -9043747200000the_geom: nulltitle: "1683"
```
```
throw new Error('start > end');
```

we have annotations where start > end

---

lib/core/time/maps.js
lib/ng/core/ogc/module.js
lib/owsjs/index.js
test/test-maps.js

This is a follow-up from #208 
Once the WMS-C parser is in JSONIX we will need to parse the resolutions array and the extent and set that in the layer config to make use of the custom tileGrid
This also involves using WMS 1.1.1 GetCapabilities parsing instead of 1.3.0 as we have now.

set tileGrid parameters from WMS-C GetCapabilities

---

lib/ng/edit/style/controllers/controllers.js
lib/ng/edit/style/services/styleTypes.js

When a user revisits the style editor, it will retain the styles that were previously applied, assuming the layer contains a `jsonstyle` member in its metadata containing the style information to be applied; or a temporary `stylestore` object exists in `window.config`. These have been implemented in MapStory Composer.

Persist Style in Style Editor

---

lib/ng/edit/style/controllers/controllers.js
lib/ng/edit/style/services/styleTypes.js

In order to persist styles in the style editor, the code was initially written to extend the style being passed to the editor using the layer's style. This was overwriting necessary attributes contained in the original style object.

Add stroke and symbol to style rather than extending object.

---

lib/ng/edit/style/directives/directives.js

`styleType` isn't declared, which results in an error if the `use strict` directive is present.

Declare `styleType` to prevent errors.

---

dist/story-tools-edit-ng.js
dist/story-tools-edit.js
lib/edit/style/styleStorageService.js
lib/ng/edit/style/directives/directives.js

This PR:
- adds var declarations for `strict` js
- adds dot notation to appease the linter

Add styleType var declaration to build file

---

dist/story-tools-core.js
gulpfile.js
lib/core/time/maps.js
lib/core/time/utils.js
package.json
test/test-utils.js

This PR:
- updates the path to the `moment` module to fix an import error
- updates the version of `karma-phantomjs-launcher` being used so that tests can be run
- removes the `docs` step from the default Gulp process

Update karma-phantomjs-launcher version and fix moment filepath

---

dist/story-tools-core-ng.js
lib/ng/core/pins/module.js

***This PR should be merged in along with this one: https://github.com/MapStory/mapstory/pull/456***
If a point in the timeline doesn't intersect the pin's timeline range, emit 'hidePinOverlay', which will be used by the MapStory viewer to close any overlays that no longer belong on the map.

Emit hidePinOverlay if pin is not in range.

---

dist/story-tools-core-ng.js
lib/ng/core/mapstory/module.js
lib/ng/core/mapstory/services/localStorageSvc.js
lib/ng/core/mapstory/services/remoteStorageSvc.js
lib/ng/core/mapstory/services/services.js

This is some scaffolding work. I'm breaking the `mapstory` ng module into several services that get bundled into `storytools.core.mapstory`, beginning with the local and remote storage services. The remote storage service isn't finished yet. For now it's included as a placeholder. I also plan on moving the style storage service out of the core Node library and into the mapstory directory to also be wrapped into the module, since it won't be used outside of a browser context.

Add storage services to mapstory module

---

bower.json
gulpfile.js

This PR resolves https://github.com/MapStory/mapstory/issues/652 and does the following:
- Removes built files from the bower.json `main` entry
- Adds a resolution entry for Angular 1.6.3
- Updates Angular-mocks to the correct version of Angular
- Removes `docs` from the default Gulp task
- Simplifies the default Gulp task

Improve Karma Configuration

---

lib/ng/core/time/services.js

Allows timeline to be updated when there are no storylayers and you add/remove boxes and annotations #243
The issue can be recreated by using the storystools composer:
1. Add a storypin or box
2. Notice the timeline appears
3. Remove the storypin or box
4. Notice the timeline isn't updated to reflect the removal feature

Allow timeline to be updated..

---

dist/story-tools-core.js
lib/core/time/slider.js

Story-tools updates the time slider range asynchronously as layers are loaded. This PR ensures that the slider gets updated with the most current range.
Resolves https://github.com/MapStory/mapstory/issues/626

Update slider range to account for async behavior

---

lib/edit/style/SLDStyleConverter.js
lib/ng/edit/style/directives/directives.js
lib/ng/edit/style/services/styleChoices.js
lib/ng/edit/style/services/styleTypes.js
lib/templates/edit/style/widgets/label-editor.html

Fixed styling options for label outlines, had to remove `Shadow` option as SLD does not support it. `Cursive` as a font option had to be removed as an option because GeoServer does not have any cursive fonts available in the default installation.
https://github.com/MapStory/story-tools-composer/issues/103

103 label outlines
