examples/style-example.html, examples/style-example.js, lib/edit/style/SLDStyleConverter.js, test/test-SLDStyleConverter.js
=> Add local WMS layer option with SLD_BODY to style example

examples/style-example.js, lib/edit/style/WPSClassify.js, lib/ng/edit/style/controllers/controllers.js, lib/ng/edit/style/services/layerClassificationService.js, lib/ng/edit/style/services/services.js, lib/ng/edit/style/services/styleChoices.js
closes #87 
closes #86 
closes #83
=> Wps classify improvements

examples/style-example.js, lib/edit/index.js, lib/edit/style/WFSDescribeFeatureType.js, lib/ng/edit/style/services/layerClassificationService.js, lib/ng/edit/style/services/services.js
=> Use WFS DescribeFeatureType to get info about layer

examples/common.js
closes #95 
see also #73 for switching to fixed strategy
=> Use fixed strategy instead of BBOX, more vector styling

lib/edit/style/WPSClassify.js, lib/ng/edit/style/services/layerClassificationService.js
=> implement unique classification

examples/common.js, examples/full-example.html, examples/full-example.js, examples/index.html, examples/templates/add-layers.html, examples/templates/layer-list.html, gulpfile.js, lib/edit/style/WFSDescribeFeatureType.js, lib/ng/core/time/services.js, lib/ng/edit/boxes/directives.js, lib/ng/edit/boxes/module.js, lib/ng/edit/pins/directives.js, lib/ng/edit/pins/module.js, lib/ng/edit/style/controllers/controllers.js, lib/templates/edit/boxes/box-chooser.html, lib/templates/edit/boxes/box-editor.html, lib/templates/edit/boxes/boxes-editor.html, lib/templates/edit/pins/pin-chooser.html, lib/templates/edit/pins/pin-editor.html, lib/templates/edit/pins/pins-editor.html
- design similar to intended working final look
- cleanup and unify some logic from other examples into common
- add placemarks for boxes and pins
breaks:
- other examples
=> start 'full' example, incomplete and breaking

examples/common.js, lib/templates/edit/style/widgets/classify-editor.html, lib/templates/edit/style/widgets/label-editor.html, lib/templates/edit/style/widgets/symbol-editor.html
=> Fix up atttribute combos

lib/ng/edit/style/style.less, lib/templates/edit/style/widgets/classify-editor.html, lib/templates/edit/style/widgets/label-editor.html, lib/templates/edit/style/widgets/symbol-editor.html
=> scroll issue for attributes in full example

examples/full-example.js, lib/edit/style/SLDStyleConverter.js, lib/edit/style/WFSDescribeFeatureType.js, lib/ng/edit/style/controllers/controllers.js, lib/ng/edit/style/services/layerClassificationService.js
=> default vector style does not match default style of style editor

lib/edit/style/WFSDescribeFeatureType.js, lib/ng/core/style/ol3StyleConverter.js, test/test-ol3StyleConverter.js
=> Implement vector classification for polygons

lib/edit/style/SLDStyleConverter.js, test/test-SLDStyleConverter.js
=> Implement SLD PolygonSymbolizer

examples/common.js, examples/full-example.js, examples/templates/layer-list.html, lib/core/time/models.js, lib/ng/core/time/services.js
E.g. reading the playback mode, supporting more layer types
=> More complete implementation of map config loading

examples/common.js, examples/full-example.js, lib/core/time/maps.js, lib/core/time/models.js, lib/ng/core/time/services.js
as WMS or as vector but seem to not work anymore
=> adding mapstory layers is broken

examples/common.js, lib/edit/index.js, lib/edit/style/StyleComplete.js, lib/ng/edit/style/services/layerClassificationService.js, lib/ng/edit/style/services/services.js, lib/ng/edit/style/services/styleTypes.js, test/test-StyleComplete.js, test/tests.js
More to come, but let's get this in first.
=> Some fixes to the styling system

lib/edit/style/SLDStyleConverter.js
see #132 
this still needs tests
=> icon coloring and opacity in SLD

examples/common.js, examples/full-example.html, gulpfile.js, lib/core/time/maps.js, lib/mapstory/MapConfig.js, lib/mapstory/index.js, test/test-maps.js
=> Move map config code into separate library part

examples/common.js
=> Do not use the overhead of ServerVector

examples/full-example.js
small fix so that initial state of playback options dialog is correct
=> Make sure playback options has the right mode for saved maps

examples/common.js, lib/mapstory/MapConfig.js
=> when loading map config retrieve layerInfo over XHR

lib/ng/edit/style/services/layerClassificationService.js, lib/templates/core/error-dialog.html
=> Show error dialog when WPS execution fails

lib/templates/edit/style/types/class-point.html, lib/templates/edit/style/types/class-polygon.html
=> choropleth shows symbol dialog which doesn't make sense

lib/mapstory/MapConfig.js
As pointed out by @ischneider, the old code did not work for all cases use llbbox instead
=> Use llbbox from GetCapabilities

examples/common.js
This fixes loading mapstory map 2164
=> Make sure our XHR request for DescribeFeatureType is a relative one

examples/common.js
=> Make sure our extent matches the one from GWC

lib/mapstory/MapConfig.js
it shows up correctly in the style pane though
=> when loading from local storage layer title does not show up

lib/mapstory/MapConfig.js
Used for instance in: http://mapstory.org/maps/1196/view/
=> add support for gxp_mapboxsource

examples/common.js, examples/templates/layer-list.html, lib/mapstory/MapConfig.js
so people can select the base layer in the map they compose
=> add base layer selection

examples/common.js, lib/mapstory/MapConfig.js, test/test-MapConfig.js
=> More baselayers

lib/mapstory/MapConfig.js
Used for instance in: http://mapstory.org/maps/1195/view/
=> add support for gxp_mapquestsource

lib/mapstory/MapConfig.js
=> Make sure normal OSM maps still work

lib/core/time/maps.js, lib/mapstory/MapConfig.js
when loading up http://localhost:8001/examples/full-example.html#/maps/1192/data/
some layer seems messed up, need to investigate more:
=> failure to load map 1192

examples/common.js
which is needed for the storyboxes
=> implement allowPan and allowZoom on the mapManager

examples/common.js
Prepare functionality for storyboxes
The animation will likely need tuning and/or might need to be configurable when creating the map story.
=> Add a first animation for story boxes

examples/full-example.html, gulpfile.js, karma.conf.js, lib/edit/style/SLDStyleConverter.js, lib/edit/style/WFSDescribeFeatureType.js, lib/edit/style/WPSClassify.js, lib/owsjs/index.js
The idea would be to create a bundle separate from the edit bundle as it's likely these dependencies will change less and we can leverage caching. This could be a global export module
Low priority
=> jsonix and mappings as separate bundle

examples/common.js
=> Fix up the broken add vector layer functionality

examples/composer.js, examples/templates/layer-list.html, lib/ng/core/ogc/module.js
=> Ability to change layer type

examples/composer.js, examples/templates/layer-list.html
in composer, the default base layer is MapQuest, but the combo box does not show this correctly.
=> select base layer doesn't have correct setting on load new map

lib/ng/core/ogc/module.js
Otherwise we get a circular error
=> Do not serialize features on a vector layer

examples/composer.js, lib/ng/core/ogc/module.js, lib/ng/core/pins/module.js
This was work done by @ischneider which might need some finishing, but opening up a PR so we don't forget about it.
=> heatmap wip + partial fix for loading annotations

examples/index.html
The broken examples routes are confusing for new developers.
=> Update example routes.

dist/story-tools-edit-ng.js, lib/ng/edit/style/controllers/controllers.js, lib/ng/edit/style/services/services.js, lib/ng/edit/style/services/styleStorageService.js, lib/ng/edit/style/services/styleTypes.js, test/test-styleStorageService.js, test/tests.js
This PR implements styling persistence within the style editor for all style types, including those that are rule based. Both lib and dist files are included.
=> Rule based styling persistence for style editor

dist/story-tools-edit.js, lib/edit/style/styleStorageService.js, test/test-styleStorageService.js
This makes the chapter index explicit when loading layer styles.
=> Pass chapter as optional argument to getSavedStyle

dist/story-tools-edit.js, lib/edit/style/styleStorageService.js
erroneous lines included in previous commit are removed
=> rm erroneous lines

dist/story-tools-core-ng.js, dist/story-tools-core.js, dist/story-tools-edit.js, lib/core/time/line.js, lib/core/time/maps.js, lib/core/time/utils.js, lib/edit/style/WFSDescribeFeatureType.js, lib/ng/core/time/services.js
This PR addresses several issues:
1. Performance improvement to the timeline rendering when there are thousands of intervals
2. Safely parse the WFS response when there are more than one time attribute.
3. Added sha1 function used for the unique id generation
4. fixed wfs handling
=> Fix core issues found durning testing.

dist/story-tools-core-ng.js, lib/ng/core/ogc/module.js
Resolves https://github.com/MapStory/mapstory/issues/365
=> Add min/max zoom params to layer map

dist/story-tools-core-ng.js, dist/story-tools-mapstory.js, lib/mapstory/MapConfigTransformer.js, lib/ng/core/ogc/module.js
This PR resolves:
- https://github.com/MapStory/mapstory/issues/413
- https://github.com/MapStory/mapstory/issues/365
=> Add OSM Basemap Support & Min/Max Zoom Parameters 

dist/story-tools-core-ng.js, lib/ng/core/pins/module.js
John W wrote a media service that allows media from whitelisted sites to be embedded in Story-tools pins. This incorporates the logic into Story-tools. Since Story-tools is on the cusp of a major refactor, and the master branch isn't the canonical branch, I didn't devote too much time to making this current refactor neat and orderly.
=> Add John W's Media Service to Story-tools

gulpfile.js, lib/core/time/maps.js
This PR bundles the owsjs library into the full build script and also refactors the way time data is handled following a get capabilities request.
=> Return time dimension on getCapabalities request

dist/story-tools-core-all.js, dist/story-tools-core-ng.js, dist/story-tools-core.js, lib/core/time/maps.js
The `/dist` files currently on master are not in sync with the code in the `/lib` directory. This PR resolves that, and also fixes an iteration statement in `lib/core/time/maps.js`.
=> Update built files and fix dimension iteration

gulpfile.js
Improve https://github.com/MapStory/mapstory/issues/643
=> Add Bootstrap to vendor bundles

dist/story-tools-core-all.js, lib/core/time/slider.js
This PR ensures that slider options are updated on chapter change. 
Resolves https://github.com/MapStory/mapstory/issues/615
=> Pass all options to slider update

bower.json, gulpfile.js
Resolves https://github.com/MapStory/mapstory/issues/828
=> Update ui-bootstrap version and include in vendor bundle.

dist/story-tools-core-all.js, dist/story-tools-core-ng.js, gulpfile.js, lib/ng/core/pins/module.js
I'll link to them.filling in more notes shortly
https://github.com/MapStory/mapstory/issues/880
=> Self-contained angular dependency, bump code to 1.6

bower.json, gulpfile.js, lib/owsjs/index.js, package.json
This is based on the wip/mapstory branch.  This will be a longer more complex PR but the commits should be reasonably cherry-pickable.
=> WIP - Style edit updates

bower.json, gulpfile.js, lib/owsjs/index.js, package.json
Reverts MapStory/story-tools#279
=> Revert "WIP - Style edit updates"

lib/core/time/line.js, lib/ng/core/time/services.js
Some needed changes for Timeline integration of StoryFrames and StoryPins.
=> composer timeline integration

lib/templates/core/time/playback-controls.html
Fixes issue [112](https://github.com/MapStory/story-tools-composer/issues/112)
=> Fix missing tooltips on playback menu bar.

lib/edit/style/WFSDescribeFeatureType.js
Addresses https://github.com/MapStory/story-tools-composer/issues/163
=> Fix field type entries.

lib/edit/style/WFSDescribeFeatureType.js, lib/ng/edit/style/directives/directives.js
- add type namespacing
- add strings to unique styling,
- temporarily disable unique styling of integer field types
=> Add type namespacing & more

lib/ng/core/style/svgIcon.js, lib/ng/edit/style/services/iconCommons.js, lib/ng/edit/style/services/layerClassificationService.js, lib/templates/edit/style/widgets/graphic-editor.html, lib/templates/edit/style/widgets/icon-commons-search.html
Resolves https://github.com/MapStory/story-tools-composer/issues/193
=> Fix Icon Commons

lib/core/time/line.js
Changed timeline callback to use different callbacks for frames and storypins.
=> Created sepparate callbacks for pins and frames.

lib/core/time/controls.js, lib/ng/core/time/services.js
Use the native Composer function to navigate between chapters. Depends on https://github.com/MapStory/story-tools-composer/pull/225
=> Use native Composer `nextChapter` func.

lib/edit/style/SLDStyleConverter.js, lib/ng/edit/style/directives/directives.js, lib/ng/edit/style/services/styleChoices.js, lib/ng/edit/style/services/styleTypes.js, lib/templates/edit/style/widgets/symbol-editor.html
https://github.com/MapStory/mapstory/issues/1398
=> Added ability for user to use normal icon coloring

lib/templates/edit/style/widgets/stroke-editor.html
https://github.com/MapStory/story-tools-composer/issues/94
=> Fixed stroke-type dropdown in styline panel

lib/ng/edit/style/services/iconCommons.js
https://github.com/MapStory/mapstory/issues/316
=> Show icons on first load rather than requiring a search
